### PR TITLE
Allow Faraday dependency up to v2.0

### LINKED ISSUE #394: Relax faraday requirements
Hello, 

The `faraday` gem is currently restricted to `v1.1.0`, whereas the latest stable version is `1.8.0`. Would it be possible to relax faraday requirements? I'd looking to implement a couple custom Faraday middlewares and would prefer to base this work off the latest version.

### PR DESCRIPTION
**Pull request by gerbal**
This PR closes #394 and allows Faraday versions up to v2.0

### CODE REVIEW

**Comment by yuichiu416** [comment]
This works like a charm, it would be awesome if we can merge it and release an update

**Comment by corsonknowles** [comment]
Thank you for doing this! Any blockers on releasing this?

**Comment by corsonknowles** [comment]
@gaorlov What do you think of this?

**Comment by tilo** [comment]
@gaorlov would it be possible to get this PR merged soon? Faraday is changing their API

**Comment by dpep** [comment]
this is great, thanks @gerbal 🚀   any reason why we need the upper constraint, eg `< 2.0` ?

**Comment by gaorlov** [comment]
Thanks for your contributions. `1.21.0` is now live

**Comment by gaorlov** [comment]
I kept it capped under 2.0, because it is unclear what breaking changes forced the major version bump

**Pull request merged**
