### PR TITLE
call super from inherited method so that it will execute parent classes' implementations

### LINKED ISSUE #360: Implementation of `inherited` method doesn't call `super`
Version 1.16 of this gem introduces a new method `inherited` here

https://github.com/JsonApiClient/json_api_client/blob/7b7e8ec154eeb332421766b174f2e0e9b962c440/lib/json_api_client/resource.rb#L111

All implementation of `inherited` that I have seen so far calls `super` in them so that the parents' implementation of `inherited` are called.

Examples:
https://github.com/rails/rails/blob/02ecdf61d151ec3c852585c93942d0ea2ed2bd22/activesupport/lib/active_support/descendants_tracker.rb#L56
https://github.com/rails/rails/blob/affa3f8661fa916c4e80f9a68be16ba877ada3a8/actionpack/lib/action_controller/metal/rendering.rb#L23
https://github.com/rails/rails/blob/6d37c6c41a808d0f52b110d9bc1c71af8201900e/activesupport/lib/active_support/execution_wrapper.rb#L99

I will make a PR soon to add `super` to method `inherited` in that file.

### PR DESCRIPTION
**Pull request by mqchau**
Fixes #360

### CODE REVIEW

**Comment by mqchau** [comment]
@lcpriest @gaorlov You two were involved in the PR https://github.com/JsonApiClient/json_api_client/pull/346 that introduced this method.

**Comment by gaorlov** [comment]
This looks good. Thanks for the PR! Can you please update the `unreleased` section of the changefile?
Thanks!

**Comment by mqchau** [comment]
@gaorlov done

**Comment by gaorlov** [comment]
@mqchau, `1.16.1` with your fix is live. Thanks so much for your contribution!

**Pull request merged**
