### PR TITLE
feat: Add the ability to override getter for JsonApiClient::Resource id

### PR DESCRIPTION
**Pull request by randyv12**
Hello, I just want to ask and see if we can modify a single line in one file ```included_data.rb```. I ran into an issue needing to add a method id that will normalize the raw ids into integers, in cases of belongs_to, relationships.  Please see test file [here](https://github.com/JsonApiClient/json_api_client/pull/378/files#diff-80ebf7f95a92f4b80c2d68d01a357a4c393391ebe365649aa7e45da9ffc62da5R10).

**Desired Functionality:**
  I want to be able create a base class that overrides the id method of a resource and consistently return it as an integer.  Because I want to be able to transform back, the original type of my resource id.

This happens when we serialize active record / application record objects from mysql through json-apiserializer gem.
Their representation of id's turn into strings, that's how the json api documentation declares it so.

There seems to be only a one-liner change so that we can override the id method of a JsonApiClient::Resource

This adds the ability to create a subclass of JsonApiClient::Resource to have a modified id method that returns the id as an integer.  This gives the application code the flexibility to match against attributes (ids of type integer) of other resources that are integers, which weren't translated to strings, (from gems such as json-apiserializer).

### CODE REVIEW

**Comment by gaorlov** [comment]
while this is strictly speaking against the spec, i think the change is reasonable.
can you please fix the tests and add an entry to the `##Unreleased` section of the changelog?
Thanks!

**Comment by randyv12** [comment]
Tests seems to pass:
```
242 runs, 735 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/xxx/Dev/json_api_client/coverage. 2908 / 2977 LOC (97.68%) covered.
 json_api_client % rake test

```

**Comment by randyv12** [comment]
Oh I see, the method name in one of the test was incorrectly prefixed without ```test_``` .  Updated.

**Review by gaorlov — CHANGES_REQUESTED** [review]
Looks great! thanks for contributing!
Please merge in main to get tests running in the PR
Thanks!

**Comment by randyv12** [comment]
would you like me to fix those tests for different ruby versions? i think its got to do with Fixnum vs Integer

**Comment by gaorlov** [comment]
> would you like me to fix those tests for different ruby versions? i think its got to do with Fixnum vs Integer
That would be ideal, yea. Thanks!

**Review by gaorlov — APPROVED** [review]

**Comment by gaorlov** [comment]
[1.21.1](https://github.com/JsonApiClient/json_api_client/releases/tag/v1.21.1) is now live. Thanks for your work and patience!

**Pull request merged**
