### PR TITLE
Extract adding errors into a method when saving a resource

### PR DESCRIPTION
**Pull request by csmuc**
I want to customize the way the errors are added when saving a resource. I want to do some i18n things instead of directly using what's been returned by the server side.

Extracting that specific code into a `Resource#add_error` method enables me to do some clean monkey-patching (instead of copying the whole `save` method).

### CODE REVIEW

**Comment by csmuc** [comment]
@chingor13 ping 😄

**Comment by chingor13** [comment]
Can you add a test so that we don't break this in the future?

**Comment by csmuc** [comment]
Not sure how a test case could look like, because there is no change of functionality. mocks/stubs?

BTW, I want to support the "code" of an error response, like this:

```
    def add_error(error)
      if error.source_parameter
        error_attribute = self.class.key_formatter.unformat(error.source_parameter)
        
        if error.code && respond_to?(error_attribute)
          errors.add(error_attribute, error.code.to_sym)
        else
          errors.add(error_attribute, error.title || error.detail)
        end
      else
        errors.add(:base, error.title || error.detail)
      end
    end
```

The codes are "taken" or "invalid" and can be mapped to different languages with Rails i18n. Are you open to adding this feature? Then I would extend this PR.

**Comment by csmuc** [comment]
I created another PR, which features support of the "code" attribute:
https://github.com/chingor13/json_api_client/pull/265

**Comment by senid231** [comment]
Hi @csmuc 
Looks like it already extracted into `#fill_errors` at [lib/json_api_client/resource.rb:415](https://github.com/JsonApiClient/json_api_client/blob/master/lib/json_api_client/resource.rb#L415)

take a look  at PRs #275 and #277 for more details

**Pull request closed without merging**
