### PR TITLE
Support gzip content encoding

### PR DESCRIPTION
**Pull request by stokarenko**
Nothing special, just adding `::FaradayMiddleware::Gzip` Faraday middleware in order to take an advantage of Gzipped response body )

### CODE REVIEW

**Comment by stokarenko** [comment]
@gaorlov Hi again )

Is there a chance to merge this? )

**Comment by gaorlov** [comment]
Absolutely! I'll have it out by end of day tomorrow! Thanks for the work!

**Comment by stokarenko** [comment]
FYI default router (dokku, k8s etc) will not Gzip JSON-API responses because of custom `application/vnd.api+json` mime type which differs from supported by default `application/json` one. Typically it's needed to apply some Ops efforts before you will see Gzipping in action )

**Comment by stokarenko** [comment]
Probably we can add this hint in readme )

**Comment by gaorlov** [comment]
@stokarenko `1.16.0` is now live. Sorry about the delay and thanks once again for your hard work!

**Pull request merged**
