### PR TITLE
feat: Use the association options to lookup relationship class

### PR DESCRIPTION
**Pull request by sebasjimenez10**
Hey there,

I'm opening this PR because I noticed an issue with the way the association class types are being looked up when including related resources.

I discovered this when having cross-referenced types when using namespaces, like the example suggests:
```ruby
module CrossNamespaceTwo
  class Nail < TestResource
    property :size
  end
end

module CrossNamespaceOne
  class Hammer < TestResource
    property :brand

    has_many :nails, class: CrossNamespaceTwo::Nail
  end
end
```

In this case whenever the IncludedData class was initializing an instance, the utils class would not be able to produce a correct type to use for the related included type producing an error similar to the following:
```
Finished in 0.447569s, 538.4645 runs/s, 1619.8620 assertions/s.

  1) Error:
AssociationTest#test_cross_namespace_resource_references:
NameError: uninitialized constant CrossNamespaceOne::Hammer::Nail
```

Since one should be able to add options to the association definition the `class` option makes sense here. This PR makes use of that to try and figure out the appropriate type before defaulting to the existing behavior.

Thanks in advance for taking a look!

### CODE REVIEW

**Comment by sebasjimenez10** [comment]
Hey @gaorlov 👋 hope you can take a look at this one as well 🙂 thanks in advance!

**Comment by gaorlov** [comment]
@sebasjimenez10 thanks for the contribution!
This looks very similar to the built in `class_name` functionality?
```ruby

module CrossNamespaceOne
  class Hammer < TestResource
    property :brand

    has_many :nails, class_name: 'CrossNamespaceTwo::Nail'
  end
end
```
would that work for your usecase?

**Comment by sebasjimenez10** [comment]
@gaorlov thanks for the response! I went ahead and commented the changes I made to `utils.rb` and used `class_name` but I still go the:
```
NameError: uninitialized constant CrossNamespaceOne::Hammer::Nail
```

**Comment by sebasjimenez10** [comment]
@gaorlov small bump on this one as well! 🙏

**Review by gaorlov — CHANGES_REQUESTED** [review]
Looks great! thanks for contributing!
Please merge in main to get tests running in the PR and please add this PR to the `CHANGELOG.md`
Thanks!

**Comment by sebasjimenez10** [comment]
@gaorlov thanks for the reply! Merged in main into the branch and added the changelog updates!

**Comment by sebasjimenez10** [comment]
@gaorlov small bump! 🙏

**Review by gaorlov — APPROVED** [review]

**Comment by gaorlov** [comment]
@sebasjimenez10 I'm on a trip right now, but i will merge and release a new version when I'm back next week. Thank you for your contributions and patience!

**Comment by sebasjimenez10** [comment]
@gaorlov small bump! we're almost there! 🙏

**Comment by gaorlov** [comment]
hello!
Sorry about the delay! this is not available in `1.22.0`
Thank you so much for your contribution!

**Pull request merged**
