### PR TITLE
Remove depredated faraday_middleware

### PR DESCRIPTION
**Pull request by tapajos**
## Description

Faraday Middleware is [now deprecated](https://github.com/lostisland/faraday_middleware#%EF%B8%8F-deprecation-warning-%EF%B8%8F).

Replace deprecated gzip middleware for [faraday-gzip middleware](https://rubygems.org/gems/faraday-gzip)

### CODE REVIEW

**Review by gaorlov — CHANGES_REQUESTED** [review]
Looks great! thanks for contributing!
Please merge in main to get tests running in the PR and please add this PR to the `CHANGELOG.md`
Thanks!

**Comment by tapajos** [comment]
> Looks great! thanks for contributing! Please merge in main to get tests running in the PR and please add this PR to the `CHANGELOG.md` Thanks!

@gaorlov done

**Comment by lavoiesl** [comment]
Included in https://github.com/JsonApiClient/json_api_client/pull/412 and a mention was added in the CHANGELOG

**Comment by tapajos** [comment]
Closing since it was included in https://github.com/JsonApiClient/json_api_client/pull/412

**Pull request closed without merging**
