### PR TITLE
use HashWithIndifferentAccess, instead of symbolize_keys

### PR DESCRIPTION
**Pull request by tilo**
use HashWithIndifferentAccess, instead of symbolize_keys

### CODE REVIEW

**Comment by tilo** [comment]
@chingor13, @gaorlov could you please review?

**Comment by gaorlov** [comment]
This looks great! Can you please update the changelog md?
Thanks for taking the time!

**Comment by ryanbahniuk** [comment]
Thanks @tilo this will be a big help for us.

**Comment by tilo** [comment]
@gaorlov CHANGELOG is updated

**Comment by gaorlov** [comment]
i meant to mention this earlier: what's the thinking behind adding pry to the gemspec? The approach so far has been to try to keep the gemspec footprint to a minimum unless absolutely necessary. Do you feel that it's necessary?
Thanks!

**Comment by tilo** [comment]
I only added it as a development dependency, so that anyone is working on a pull request can use `pry` locally.
It will not be included as a dependency for any project using `json_api_client`

**Comment by tilo** [comment]
@gaorlov do you think it's good to go, or do you want me to remove `pry`?

**Comment by gaorlov** [comment]
The approach so far has been to keep the dependency footprint - both dev and release - to the minimum necessary to run and test. However, if you feel strongly that the addition of pry will benefit the gem I don't have any strong opposition to it. 
Again: thank you for taking the time and your contribution!

**Comment by tilo** [comment]
I removed `pry` from this PR, and added a separate PR here: https://github.com/JsonApiClient/json_api_client/pull/385

**Comment by gaorlov** [comment]
`1.19.0` is now live with your changes. Thanks for contributing!

**Pull request merged**
