### PR TITLE
fix issue #352: relationships w/o included data

### PR DESCRIPTION
**Pull request by dugsmith**

### CODE REVIEW

**Comment by dugsmith** [comment]
Hey @gaorlov, I think this will be a relatively quick one, if you agree with the issue #352 and my fix.

**Comment by gaorlov** [comment]
Thanks a ton for taking the time!

**Comment by dugsmith** [comment]
@gaorlov: Thanks! I made the changes you requested.

**Comment by dugsmith** [comment]
@gaorlov Great! Thanks for the quick turnaround! :-)

**Comment by gaorlov** [comment]
@dugsmith `1.14.1` is live. Thanks so much for the contribution!

**Comment by dugsmith** [comment]
@gaorlov Excellent! Thank you! :-)

**Pull request merged**
